model:
  baseline: 
    loss_function: MultiLogloss  
    depth: 6    
    l2_leaf_reg: 1 
    iterations: 500 
    learning_rate: 0.05
    verbose: 100
  tune:
    cv: 5
    metric: neg_log_loss
    search:
      depth: [4, 6]
      learning_rate: [0.01, 0.05, 0.1]
      l2_leaf_reg: [1, 3]
      iterations: [500, 750]
data:
  label: Title
  features: ["Column 1", "Column 2", "Column 3", "Column 4"]
  test_size: 0.3